name: dsl-final-project
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  # - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.21
  - pip:
    - pandas
    - accelerate==0.17.0
    - tensorboard
    - transformers