name: rationallama
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.10
  - pip
  - pytorch
  - pytorch-cuda=11.8
  - bitsandbytes
  - peft
  - numpy
  - pandas
  - scikit-learn
  - transformers
  - kaggle
  - sentencepiece
  - protobuf
  - datasets
  - ipykernel
  - tqdm
  - pip:
    - wandb
    - accelerate
    - flash-attn
    - openai